### ISSUE TITLE
Are these features available, or can they be implemented?

### ISSUE THREAD

**Issue by chuyinluotian01** [legend2ks/YoutubeDownloader#18]
![20da714a0cd6f8c6b80e6884e7c0f634](https://github.com/legend2ks/YoutubeDownloader/assets/53629507/d9413e0d-84db-4ec1-84ee-b2c690d7ab8a)
Could you add a feature to check if a link already exists in the download list, and if it does, do not add it again or show a prompt?

![image](https://github.com/legend2ks/YoutubeDownloader/assets/53629507/eb9a0c6c-fe79-41e3-9e15-4dd9ae5bf6ee)
Also, after adding the links, they need to be clicked one by one to start the download. Is there an option to select and download them in bulk?

**Comment by legend2ks** [comment]
1. Yes, I will add this feature if I have time.
2. You can select multiple items > Right-click > Enable

**Comment by chuyinluotian01** [comment]
3Q

**Comment by chuyinluotian01** [comment]
3Q
