### ISSUE TITLE
Windows Defender Alert

### ISSUE THREAD

**Issue by Kaschtelator** [legend2ks/YoutubeDownloader#20]
![image](https://github.com/legend2ks/YoutubeDownloader/assets/61439673/1ac5f54b-f0d6-4ba4-b651-b1314722e7f8)

Threat removed.

Severe /\
06/13/2024 1:03 PM

Detected: Behavior:Win32/DefenseEvasion.Atml
Status: Removed
A threat or app was removed from this device.

Date: 06/13/2024 1:04 PM
Details: This program is dangerous. It executes commands from an
attacker.

**Comment by legend2ks** [comment]
It's a false possitive. You can build from source code.

**Comment by Kaschtelator** [comment]
I did and then saw that it was a false alarm

thx
