### ISSUE TITLE
Unable to refresh filename

### ISSUE THREAD

**Issue by Tontze** [legend2ks/YoutubeDownloader#25]
Selecting files downloaded from channel tab, right click, select "refresh filename", confirm it, and filename is not changed. I have only *TITLE* selected. 

Filename is changed when you add file download directly.

**Comment by legend2ks** [comment]
If the files are in their channel's folder, the filename is based on the default filename template. Because finding the downloaded video in the channels section relies on this template.
If you move the files to some other path, you should be able to rename them based on your custom template.
