### ISSUE TITLE
Autoclose on startup

### ISSUE THREAD

**Issue by mahmutelmas06** [legend2ks/YoutubeDownloader#4]
Application autoclose after icon showup immediately.
I am leaving the log below

[log20230820.txt](https://github.com/legend2ks/YoutubeDownloader/files/12388895/log20230820.txt)

**Comment by legend2ks** [comment]
Please try the latest version (v0.1.0)

**Comment by mahmutelmas06** [comment]
Thank you problem solved.

But this time Microsoft Defender warns that youtubedownloader.exe is a virus.

![resim](https://github.com/legend2ks/YoutubeDownloader/assets/11191763/28fc19c3-8efa-46b3-ac5d-a794bc49bbc3)

**Comment by legend2ks** [comment]
This is v0.0.3's scan result:
https://www.virustotal.com/gui/file/47abd2a4afed0fc4ff1d9cc9110ea656c37da78a045a75efd62afc1a32761596

And v0.1.0's:
https://www.virustotal.com/gui/file/8c525c7e5323aef909a9b494c8501a0e6524e466555d6caf3bd1bde13d7c6042

v0.0.3 was made with .NET SDK v7.0.305, and v0.1.0 was made with SDK v7.0.400. If v0.0.3 is built with the new SDK, the scan result will be exactly the same as v0.1.0 (2 flags):
https://www.virustotal.com/gui/file/2807333ac2ba341e69d42320e339a8ee0f25d46412d8f33a1d58b37023d9fa9d

I think these must be false positives. I did the build from an isolated virtual machine. There is no way that the file is infected.
