### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by ananinamisa** [legend2ks/YoutubeDownloader#5]
when i try to add channel its force closing

**Comment by ananinamisa** [comment]
[log20230911.txt](https://github.com/legend2ks/YoutubeDownloader/files/12579636/log20230911.txt)

**Comment by ananinamisa** [comment]
Can you set this for youtube shorts too?

**Comment by legend2ks** [comment]
Please try the latest version (v0.1.1). It should be fixed now.
