### ISSUE TITLE
How can i select all videos

### ISSUE THREAD

**Issue by ananinamisa** [legend2ks/YoutubeDownloader#7]
![image](https://github.com/legend2ks/YoutubeDownloader/assets/129632219/a95a8658-16c3-42a7-aa96-952fabdb0afd)

**Comment by ananinamisa** [comment]
i dont want click every one of them

**Comment by ananinamisa** [comment]
> I'm working on it.

ty i am waiting

**Comment by ananinamisa** [comment]
Also, when downloading videos, the download speed is very slow, for example, when there is 10% left to download, the download speed becomes even slower.

**Comment by ananinamisa** [comment]
> I'm working on it.

when will you fix it sir ?

**Comment by legend2ks** [comment]
In a few hours

**Comment by legend2ks** [comment]
New release (v0.2.0) is up.

**Comment by ananinamisa** [comment]
tysm your best
